# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21cf2b5ee3029a88ca9963549eba4a811c869e9ca15389adab8b070f6a95a7ac9ffc8700090412e539f56ff2240a6171e71445fe247fe5bce3402a91cdf67c98

test:
  secret_key_base: cfb7794baaaec89937b4d6698ed9ab96048bc9943322a0c2e17d075055645516d49a0485513a9589b745fb720ecd631de635fc64baf8a610c2499bf3323f8c3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
